### ISSUE TITLE
nfsbroker not respecting no_proxy variable

### ISSUE THREAD

**Issue by lameventanas** [cloudfoundry/nfsbroker#26] opened 2020-04-25 07:54 UTC
I have deployed my bosh environment using the `misc/proxy.yml` ops file and the `http_proxy`, `https_proxy` and `no_proxy` variables.
Now when I try to run the nfs-broker-push errand I get this error message:
```Instance   nfs-broker-push/7c4237ec-0176-4f2d-bd89-ebc902d789a1
Exit Code  1
Stdout     cf version 6.49.0+d0dfa93bb.2020-01-07
           Logging out ...
           OK

           Setting api endpoint to https://api.cf.test.org...
           FAILED

Stderr     Request error: Get https://api.cf.test.org/v2/info: dial tcp 10.125.0.2:443: connect: connection refused
           TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
```

**Comment by julian-hj** [comment] 2020-04-27 23:46
@lameventanas Hi, sorry, I am not familiar with the ops file you are referring to.  Can you point us to the `misc/proxy.yml` ops file you used?  Also, can you tell us which settings you were using?

Normally proxy settings in CF are applied to running application containers, not bosh VMs, but without knowing exactly what you are trying to do, it's hard to speculate about why it isn't working.

**Comment by lameventanas** [comment] 2020-04-28 06:47
I'm using this via cf-deployment, that's where the ops file is, and the director is created using the proper `HTTPS_PROXY`, `HTTP_PROXY` and `NO_PROXY` variables.

I tried by using:
`NO_PROXY="test.org,internal,10.125.0.2,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"`
and also:
`NO_PROXY="test.org,cf.test.org,internal,10.125.0.2,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"`

It seems that the `NO_PROXY` variable is ignored, but the `HTTPS_PROXY` isn't, so it's trying to connect to `api.cf.test.org` via the proxy. (`api.cf.test.org` resolves to `10.125.0.2`).

**Comment by julian-hj** [comment] 2020-04-28 16:25
I see.  The nfsbrokerpush errand is really just a bash script that invokes the cf cli: 
https://github.com/cloudfoundry/nfs-volume-release/blob/master/jobs/nfsbrokerpush/templates/deploy.sh.erb#L36

We don't do anything special to set (or unset) linux proxy environment variables.  So it seems to me that this failure is either due to
1. the bosh agent on the errand VM not setting the NO_PROXY setting when invoking the errand or
2. the CF cli not respecting the NO_PROXY setting for some reason or
3. this is unrelated to proxy settings, and you simply lack connectivity between the errand VM and the cf cli due to network policies

I'd suggest debugging this by invoking the --keep-alive option when running the errand.  That will leave the errand VM extant after the errand fails.  From there you can edit the errand script and re-invoke it to understand if the NO_PROXY setting has been passed through to the errand script.  You could also try `nc -z 10.125.0.2 443` to see if you are able to establish a direct connection to the load balancer from the errand VM.

**Comment by lameventanas** [comment] 2020-04-30 09:00
After restart the fail errand when using `--keep-alive`?
If I just ssh to the vm and run the script as root, the environment won't be the same, so it's useless.
I would start by adding a `printenv` somewhere to see what it's getting.
Also, it's probable that bosh is setting the variables uppercase (as it itself uses uppercase), while cf uses lowercase.

**Comment by julian-hj** [comment] 2020-05-05 16:21
Hi @lameventanas 

Were you able to establish whether or not you have the requisite network rules to connect to the CF api from the errand VM?

`nc` just opens a tcp connection, so it should ignore proxy settings.  If that succeeds, you could move on to curl or wget, which should pick up whatever the proxy settings are.

Failing that, I'd suggest to reach out to the BOSH team with this issue, as it really doesn't look like an NFS specific issue to me.

**Comment by lameventanas** [comment] 2020-05-05 17:47
Hi @julian-hj ,
There might be a configuration issue, I'm still trying to verify it.
In the `run` script, `cf` is trying to connect to `10.125.0.2`. Is this supposed to be the IP of the router or the api vm?

**Comment by julian-hj** [comment] 2020-05-05 19:52
I'm not fully sure what this ought to look like in your environment, but in our test environments, normally we see the same DNS resolution inside and outside of the bosh network, which means that you'd expect to see the IP address of the load balancer coming back.

Do you get a different IP address if you `dig api.cf.test.org` from a client that is able to connect to CF?

**Comment by lameventanas** [comment] 2020-05-11 03:36
There was a problem with the IP assignment that I didn't notice before due to the way cf-deployment sets up iptables, this has been fixed now.
But I still can't get nfs to work because the nfs-volume release doesn't consider the usage of proxies.

**Comment by julian-hj** [comment] 2020-05-11 16:29
OK, I am going to close this one, since the issue is resolved.  It looks like you've opened a separate issue for your nfstestserver problems, so I will response to that one in situ.

**Closed by julian-hj** 2020-05-11 16:29 UTC
Labels: scheduled
